events {}

http {
    # Define um servidor HTTP
    server {
        # Escuta a porta 80 dentro do container Nginx
        # (é mapeada para a porta 8088 no host VPS via docker-compose)
        listen 80;

        # Bloco que trata todas as requisições recebidas no caminho "/"
        location / {
            # Redireciona todas as requisições para o serviço evolution_api na porta 8080
            # Esse nome (evolution_api) é o nome do container, resolvido pela rede Docker
            proxy_pass http://evolution_api:8080;

            # Preserva o cabeçalho original do host (importante para logs e roteamento interno)
            proxy_set_header Host $host;

            # Passa o IP real do cliente para o serviço backend
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
